version: "3.7"
services:
    printful_php:
        user: dev:dev
        container_name: printful_php
        build: ./docker_config/php
        restart: always
        volumes:
            - ./${BACKEND_APP}:/var/www/printful
            - ./docker_config/php/www2.conf:/usr/local/etc/php-fpm.d/www2.conf
        working_dir: /var/www/printful
        ports:
            - "10180:9000"
        networks:
            printful_network:
                aliases:
                    - printful_php

networks:
    printful_network: